### ISSUE TITLE
*ISSUE* Cant edit public test saves *ISSUE*

### ISSUE THREAD

**Issue by Hellzbellz123** [elpatron68/SnowRunner-Tool#2]
Snowrunner tool cant seem to edit the most recent ptrs save files. not really sure why.

**Comment by elpatron68** [comment]
Hi, thanks for reporting. I have tested the tool against a PTS save game. ATM only the first save game slot can be edited (money/xp). If you consider any problems, please send me your zipped save game directory, so I can have a deeper look into that.
