### ISSUE TITLE
Cant select game profile location, and change to steam

### ISSUE THREAD

**Issue by hreich11** [elpatron68/SnowRunner-Tool#21]
Is there a way to manually slect game profile location ?  I use parameter -platfomr steam but it doesnt register, is there a way to manually setup game profile locaiton?

**Comment by elpatron68** [comment]
Hi, do you have both version (Steam **and** Epic) installed? If you selected *Steam* by adding `--platform steam` as command line argument, the profile will be determined by Steam´s registry settings `HKCU\Software\Valve\Steam\SteamPath`, which usually works fine. Maybe you could send the log file (located here: `%APPDATA%\SRT\log.txt`).
