### ISSUE TITLE
Parse save files looking for "persistentProfileData" to support New Game+ saves

### ISSUE THREAD

**Issue by Jaymus3** [elpatron68/SnowRunner-Tool#28]
The current parsing regex doesn't look for the persistent profile data, so new game+ saves just read the starting money and xp values.  Consider changing https://github.com/elpatron68/SnowRunner-Tool/blob/9891e9948f1026cf202fbcdf6cea9a5830dea36b/SnowRunner-Tool/CheatGame.cs#L38 to ``string sPattern = @"\""persistentProfileData\""(.*?)\""money\""\:\d+";`` and https://github.com/elpatron68/SnowRunner-Tool/blob/9891e9948f1026cf202fbcdf6cea9a5830dea36b/SnowRunner-Tool/CheatGame.cs#L106 to ``string sPattern = @"\""persistentProfileData\""(.*?)\""experience\""\:\d+";``.
There's a few other things related to your file writing and such that will need to be modified as well.  Attaching an example NG+ save for you to tinker with (file extension changed to log so Github will let me upload it).
[CompleteSave1.log](https://github.com/elpatron68/SnowRunner-Tool/files/11461015/CompleteSave1.log)

**Comment by elpatron68** [comment]
Thanks, this will be fixed with the upcoming release.
