### ISSUE TITLE
Leaving a co-op lobby creates an in-game vs tool money discrepancy

### ISSUE THREAD

**Issue by Jaymus3** [elpatron68/SnowRunner-Tool#29]
If a player leaves a co-op lobby and doesn't load single player again, some of their money is left in the "refundMoney" value from trailers they left in world until they load single player again.  This creates a discrepancy between the value of money shown in-game vs what your tool will actually show.  You could address this with an interface hint, an addon to the readme explaining to load into single player before editing, or parsing ``refundMoney`` and adding it to the total visually shown to the user.  Editing the money value will properly add money in-game since the game is adding these two numbers together in your current implementation.

**Comment by elpatron68** [comment]
Thanks fo reporting. I added this to the money-change dialog: 

_"Warning: If you played the last session in multi player mode, you should start in single player mode before you change the amount of money if you want your MP earnings to be transferred."_
