### ISSUE TITLE
IS it working with game pass version ?

### ISSUE THREAD

**Issue by etshy** [elpatron68/SnowRunner-Tool#40]
When i run Snowrunner tool, it says there is no save yet, even though I have a save on Gamepass.

**Comment by elpatron68** [comment]
Hi,sorry, the tool does not work with the Xbox version of the game.Am 05.11.2023 18:58 schrieb Etshy ***@***.***>:
When i run Snowrunner tool, it says there is no save yet, even though I have a save on Gamepass.
