### ISSUE TITLE
savefile no longer .dat

### ISSUE THREAD

**Issue by HY-SANG** [elpatron68/SnowRunner-Tool#5]
With savefile changed to CompleteSave.cfg, the tool no longer works. Any suggestions or next steps?

**Comment by elpatron68** [comment]
Just asking myself why they changed the file name. I will probably be able to fix it next week.

**Comment by elpatron68** [comment]
It seems like Saber has revoked the file name change. At least, my Snowrunner version (v17.3, Epic Store) creates `CompleteSave[x].dat` files again.
